name: Test Ruby

on:
  push:
  pull_request:


jobs:
  deploy_preproduction:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', head, jruby, jruby-head, truffleruby, truffleruby-head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build Example
      working-directory: example
      run: bundle exec erb-hiera --config=config.yaml --hiera-config=hiera.yaml
